services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    migrate:
        build:
            context: ./migrate
        environment:
            DATABASE_URL: "user=${DB_USERNAME} password=${DB_PASSWORD} dbname=${DB_NAME} sslmode=disable"
        depends_on:
            - postgres
        restart: on-failure
        entrypoint:
            [
                "goose",
                "-dir",
                "./migrations",
                "postgres",
                "postgres://postgres:postgres@postgres:5432/orders?sslmode=disable",
                "up",
            ]

    zookeeper:
        image: confluentinc/cp-zookeeper:7.5.0
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181

    kafka:
        image: confluentinc/cp-kafka:7.5.0
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        depends_on:
            - zookeeper

    kafka-init:
        image: confluentinc/cp-kafka:7.5.0
        depends_on:
            - kafka
        entrypoint:
            [
                "sh",
                "-c",
                "kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic ${KAFKA_TOPIC} --replication-factor 1 --partitions 1",
            ]
        restart: no
volumes:
    pgdata:
